queue_rules:
- name: edge-api
  conditions:
    - base=main
    - "#approved-reviews-by>=2"

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
    - base=main
    - "#approved-reviews-by>=2"
    - check-success=Build
    - check-success=ci.ext.devshift.net PR build
    - check-success=ci.int.devshift.net PR build
    - label!=work-in-progress
    - label!=Do not merge
    actions:
      queue:
        name: edge-api
        method: merge
        rebase_fallback: none