services: docker
language: go
go: 1.15
env:
  global:
    - FLEET_MANAGEMENT_ORG: quay.io/fleet-management
    - DEFAULT_BRANCH: main
    - secure: ARRa4MvZafDwj/5ZJe8dbrVi7X7izKmcWbBT94/wYPTXR/MJL5+p8GTpJGAcjSUqpkJLDOoXdgr7AtlHPlhYYYEu+D/FPjERVE4q5ggPXPt+3P0YBgVcSmrJpS2igWM8ha9vzynqUEpwUr4qOLq+NWGu4zZ7lV8VPaCL21hIoB+RJeXo0JLXtm/r0hfCTbR9g4M0C7B2rZV7D7hRonmmAjumKGZlI1LffVTTLVtkdqFqOaDVJLRvyBFMfTFMGa8Ow18mgut18+G3eI0jiUV74pApTa9idfbe6BF7eF3ISQcqdkDW5SdHJm1bnUGLCg9gobjOf0dM5pbZJoId6mINR0oUn2qifwFpiqOTurGqfya6GFX+1O+tIS3i0cO9HtzUWX299gGAZYxsSKMwdK7bKNyPPe64iATBZzoqGLfUfkROdYtx65BdNXW/lmScxcEiOiBLAN0IiZYhLJQ3EA14G6cc4FHmK6T20NP7hojfCWo2emmNgLFiE0Zh0fpuQVtfd6xZXcVadHX5pgPmpdSMsIwXChzgeV3p/HxIvQ3t56Oj8b0imjeQoKO9zGxzNBNZ4eAAU97SI+9M0L6uRbNXlzRjl1TbxK9ud3kNXfe7x+d0xZDMa62UgAQdH9fSfIqlhsCwLQmjAe3pMi42VL74GZWGAMADYRvkqlm4TFP+JP0=
    - secure: Zegy/7fvNJMw4eLe/myYco7mxZjLQerej3vkgbi/toMk+8ERu9i1pfE7GmAsIT2QEZ466sd70OuilspX8JLkzkyF5rViIQOl/dPU4bf6DgYW+yfDJZ4kHPnOUR5fHghZaYFgJq9jFk+EDnVzK7DoptKEWPfk2NAPCwv5Vmv0kgqvmPLG+NeVkhtx/QXalXiHcpDXSWSZaWtMdBF2RTi4VdhDIEsWKEpkK1Qr2WODNACSuyBRlG/Jd57AE3I4T4Kw3N2IlVu8G86+zlDp3B6cPh47+eauufyMCNargpZRmTAtXFMhnbpsEjgWZZ1jRvDtFiI0fHYnDHtB1AkzFt0M9Kn+9pDR7ihSBUfP785qudlNai5jH3/bPwyx/nLnbv4yQQk3Dzzi+dtPsWGOCUeDy0mQiN0uDGj71+Vysuwe3SkR1y3SzkhuSaab729sj/h7WvymueNjxVUX7EmLQ00LK5gqm5+bl1jnazIdaYKx8BEzXu5Qy8h5RqDRNUezSnnARTw3woqec3AocOYhXJalTinTEMW0HIPBZ8DMqlZCabYnJw4Dif1Xj33Y24BZshoWyO2xPiNV8pDasx+QnSsV9x9xdtN45dSe77RwPr66QHnw8R/YdOu0DIpFlfCPubb+XbyhBKNVDeINE0zDG5YKmKZmviVqBVna8X65tsBE3cc=
  jobs:
    - REPO_NAME=libfdo-data DOCKERFILE=./test-container/Dockerfile
    - REPO_NAME=edge-api DOCKERFILE=./Dockerfile
before_install:
  - |
    if [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
      export TAG="pr-${TRAVIS_PULL_REQUEST}"
    else
      export TAG="latest"
    fi
before_script:
  - |
    if [ "${REPO_NAME}" == "edge-api" ]; then
      sed -i 's|registry.access.redhat.com/ubi8/ubi|quay.io/centos/centos:8|' ${DOCKERFILE}
      sed -i 's|.*ubi-micro-build.*ubi.repo||' ${DOCKERFILE}
    fi
    if [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
      echo "LABEL quay.expires-after=3d" >> ${DOCKERFILE}
    fi
script:
  - docker build -t ${FLEET_MANAGEMENT_ORG}/${REPO_NAME}:${TAG} -f ${DOCKERFILE} .
  - docker login quay.io -u ${FLEETER_BOT} -p ${FLEETER_PASS} >/dev/null 2>&1
  - docker push ${FLEET_MANAGEMENT_ORG}/${REPO_NAME}:${TAG}
