# This playbook is meant to be an all-in-one
- name: Run the ostree update in a single play without external deps
  become: true
  hosts: localhost
  vars:
    fleet_infra_env: "@@ .FleetInfraEnv @@"
    update_number: "@@ .UpdateNumber @@"
    s3_buckets:
      prod: "rh-edge-tarballs-prod"
      stage: "rh-edge-tarballs-stage"
      perf: "rh-edge-tarballs-perf"
    repo_url: "https://{{ s3_buckets[fleet_infra_env] }}.s3.us-east-1.amazonaws.com/{{ update_number }}/upd/{{ update_number }}/repo"
    ostree_remote_name: "@@ .GoTemplateRemoteName @@"
    ostree_gpg_verify: "false"
    ostree_gpg_keypath: "/etc/pki/rpm-gpg/"
    ostree_remote_template: |
      [remote "{{ ostree_remote_name }}"]
      url={{ repo_url }}
      gpg-verify={{ ostree_gpg_verify }}
      gpgkeypath={{ ostree_gpg_keypath }}
      contenturl={{ repo_url }}
    insights_signature_exclude: "/vars/insights_signature,/vars/fleet_infra_env,/vars/update_number,/vars/ostree_remote_name"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldXSktaR3RqZG5jMU9FUXJhalZ3VGtGUmFtNHdRa0ZCYkdsSlpX
      eEZPRkl3ZHpCaVdFaFhZWFoxVlhsSUwzZElUa2s0TmsxVFJuY0tRbGwyVFdwS2RWcHBUSEpOVkc1
      T1ZtVTRkM1JNSzJodldsZHFiR3RDUlhodlJrOTFOV1FyV1hacE4zVm1aRWN4UVdZNVZsbzFSSFoz
      YUhCeWJFeHNZZ3BQYVhOQk9HOXdaa3BLV1RkNFVGRnhVMFpETTI5dVJuazJkM042U21SWVFubFBL
      MmhhVFdkSGRXMWxUR3hhYmswdmFVVjRhbFpOU0c0Mk1ETkxlSFZzQ2pka1RtaDRMMnhXWVhoc2Iz
      aHFURGxLY1dwNGJXcHRkMGxTU0hwWGJsQnVkMDR4UW5sUWNFUm1WM001UlRWalppOVRUa2hrZEhw
      T09YWk9lalI2ZFc0S2N6bExjSFpxTlZSNlNHUmpkUzlNU2pZNFlUTmFWR0oxTkdSc0wyNUJjR1JU
      WTBOeGVtMXROVkkzYTFwMVRtUk1la0pwS3pkUVJIWnFWRmw0ZFdaV1JncE9aRk5ZUmxoV01FOUZh
      Vmh0WkZOQ1QwSlhOVnB3VGpWRWNVbHJhUzluY0d0aFoxQkpSM0JaTmpWUVdrNXZSR3RPTUdOdWEw
      ZHFVVzlQU0RkM2RGVkVDbVJ4Y3pCNFlqQkJTVGhHTlRoR1MwUkNiM0pQTjNKb2RWUXJaRkZ1T0hS
      RWNFWnBkbUowWnpsa1FVRnJNa1pxVFZwSVpuTnpiMHhwWTFONFUyWnJWMklLZWpsT1UyNTZXa2x4
      YldGWlJuQkRRa2x2U3l0NFFVNW1VVkJ6VDBJMlFVWkpkV2RaTmxRd2ExSnhlVTR2V0VaRFkybEpl
      bXRHY3pBek5sVnZjMVJDWndwMU5HZGtlbUZGVWtsWlFrOTZMMlpNUkVWQmVraEdXRzlPTlZKdGVW
      UkhSVmRSUmtRMmJVcENhMHQ1YUM5dlZVTnFiRFE0UWxST2JFVlVLMmhhUVZKekNuY3ZjbGh4YlZO
      dFowSTJiVWt2WjFOa1RIQlFkR2RXWVRjemIzVm1jWHBtUkRSaVdXWmtka3BGVlV4b1ZEUnBVR3Qw
      WW5KUWRsSnBhM1Z6ZDBSMlpHb0tlRU5QZGtsdmFsb3ZaVXAzYVhkMlVsa3haMU5KZGxwbk1uRmlT
      R0UzVnpkUWJDOVpXak5VVmxod2MwbE1lWFkyY1N0elUxcEtiRXg2UVRGT2NteHRPQXBNVEN0RVJW
      QmxTVFZrWXowS1BXTkhVVlFLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: apply templated ostree remote config
      ansible.builtin.copy:
        content: "{{ ostree_remote_template }}"
        dest: /etc/ostree/remotes.d/rhel-edge.conf
    - name: run rpmostree update
      ansible.builtin.shell: rpm-ostree upgrade --allow-downgrade
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: schedule reboot when rpmostree upgraded
      ansible.builtin.shell: systemd-run --on-active=5 /usr/bin/systemctl reboot
      when: '"Staging deployment...done" in rpmostree_upgrade_out.stdout'
