# This playbook is meant to be an all-in-one
- name: Run the ostree update in a single play without external deps
  become: true
  hosts: localhost
  vars:
    fleet_infra_env: "dev"
    update_number: "1000"
    s3_region: "us-east-1"
    s3_buckets:
      prod: "rh-edge-tarballs-prod"
      stage: "rh-edge-tarballs-stage"
      perf: "rh-edge-tarballs-perf"
    repo_url: "https://{{ s3_buckets[fleet_infra_env] | default('rh-edge-tarballs-prod') }}.s3.{{ s3_region | default('us-east-1') }}.amazonaws.com/{{ update_number }}/upd/{{ update_number }}/repo"
    ostree_remote_name: "remote-name"
    ostree_changes_refs: "false"
    os_tree_ref: "rhel/8/x86_64/edge"
    ostree_gpg_verify: "false"
    ostree_gpg_keypath: "/etc/pki/rpm-gpg/"
    ostree_remote_template: |
      [remote "{{ ostree_remote_name }}"]
      url={{ repo_url }}
      gpg-verify={{ ostree_gpg_verify }}
      gpgkeypath={{ ostree_gpg_keypath }}
      contenturl={{ repo_url }}
    insights_signature_exclude: "/vars/insights_signature,/vars/fleet_infra_env,/vars/update_number,/vars/s3_region,/vars/ostree_remote_name"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldYSnFhazlOZG5jMU9FUXJhalZ3VGtGUlp6bHlkeTgzUWxrMVMz
      bENVMHR3Wnpoa1RTczVORFJuYTNwUVdtOVpibmd6ZUZSRWFYSUtMMWhLTW1ad0wweFJOMFZvY1Vk
      aWJISkRUbkJ0VUVzMVQxQlBha0pzZG5wRFQweHRVbE5zUlRSM2VuZzRRVmRoYTNoVk4yVnNLMVl6
      UkdrNFRUbFRjUXBIWm14aUsyRlNSV1kwU21OclNFMUdORE41TjIxaldYVmljV0V4UmpreFZrMXpP
      VTFVZEc4d1dGcDVPVkUxUzBkd2VrYzNkRXcwYWtseVZqZGtTRzVuQ21ZMWVsVnhPRlJxUmpKTGRH
      RkRha0prTWxOdE9VaGlNelJMTjNrdmFGbDJiV2RvVDFWcVkwcGlReTh2V1ZodFIxSlNUVXBaYWtS
      UE9WZHZNaTh3UlhZS1NFeFVSekJ0YkZndmNFaERjM0pXTWt3eVVYb3ZjblpxWlhSVmVXZHNOSFZ5
      UkZaMFRGQjNTMVl5VlRWNGRWRjRLMlEzUTI1dVdHMXJZbGg2WTNaVkt3cEhieTh3ZDNSRWVYRndh
      MHR0VlZSb1pGVXJjVkl6VkhobU0wRkdNVmx6ZFhocE1HSnhNREpRUm5FM1NXaERPVzVzU1hWclMy
      aG1RblJKYUVscU5Tc3lDazVLVDNFMU5tZHNlV1JzSzFkblVFNXRRMGxNYldOMU1VZFpiRlIzV2xs
      SEwzSktjRE5SY0VvelpEaHlVWEEwUVRSbFVHdFJaMFJOTTNWS01uSlRhV2dLVUhCNVlpOWxkbUYx
      WW1SNFRtZGFiVFZ3VVhaWFpsUXhOMkV2Y2pGV1VUZ3diVGh6TW1aelQwWkVPVFZ1ZDFsVWRqaDRO
      Rmc0Y1VsTFdEQlJibXB5YlFwallXZERZWGRwYVU5aVkweHhWbmwzVURKb05XOXpTWFZCY1N0U00z
      cFVSelZ4UWxkb1ZtbFBZWGRxYWtOalkwSlpNalZ4TkU5cU0xSXdZbmcxWldRNUNpdG9XamczWWtS
      a1MyOXhUSEp2ZW5aaWIwcGxRbXBYYWxsV1RFWldla3RCVVVaSE1HUkdlVE14VXk5VVIxSTNRbkJC
      UkZGc1JXaHBUMk5DTjNCT1RtVUtVVXBzY1ROcFdtTlpNR0ZzTDFoYWVIQk5LM0IxWWtKVlRFVjNh
      REkzT0RGUGNVZzBabk5WT0VoUGVGSkVUaXRYT1hCV2VEZE1aRU4wZHpSSVdESmhlUXBxUmxaS1Vt
      eGtkbVkwYXowS1BUTkJNamdLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: apply templated ostree remote config
      ansible.builtin.copy:
        content: "{{ ostree_remote_template }}"
        dest: /etc/ostree/remotes.d/rhel-edge.conf
    - name: run rpmostree update
      when: ostree_changes_refs=="false"
      ansible.builtin.shell: rpm-ostree upgrade --allow-downgrade
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: run rpmostree rebase
      when: ostree_changes_refs=="true"
      ansible.builtin.shell: rpm-ostree rebase "{{ os_tree_ref }}"
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: schedule reboot when rpmostree upgraded
      ansible.builtin.shell: systemd-run --on-active=5 /usr/bin/systemctl reboot
      when: '"Staging deployment...done" in rpmostree_upgrade_out.stdout'
