# This playbook is meant to be an all-in-one
- name: Run the ostree update in a single play without external deps
  become: true
  hosts: localhost
  vars:
    fleet_infra_env: "dev"
    update_number: "1000"
    s3_region: "us-east-1"
    s3_buckets:
      prod: "rh-edge-tarballs-prod"
      stage: "rh-edge-tarballs-stage"
      perf: "rh-edge-tarballs-perf"
    repo_url: "https://{{ s3_buckets[fleet_infra_env] | default('rh-edge-tarballs-prod') }}.s3.{{ s3_region | default('us-east-1') }}.amazonaws.com/{{ update_number }}/upd/{{ update_number }}/repo"
    ostree_remote_name: "remote-name"
    ostree_gpg_verify: "false"
    ostree_gpg_keypath: "/etc/pki/rpm-gpg/"
    ostree_remote_template: |
      [remote "{{ ostree_remote_name }}"]
      url={{ repo_url }}
      gpg-verify={{ ostree_gpg_verify }}
      gpgkeypath={{ ostree_gpg_keypath }}
      contenturl={{ repo_url }}
    insights_signature_exclude: "/vars/insights_signature,/vars/fleet_infra_env,/vars/update_number,/vars/ostree_remote_name"
    insights_signature: !!binary |
      TFMwdExTMUNSVWRKVGlCUVIxQWdVMGxIVGtGVVZWSkZMUzB0TFMwS1ZtVnljMmx2YmpvZ1IyNTFV
      RWNnZGpFS0NtbFJTVlpCZDFWQldYSnFhWEp6ZG5jMU9FUXJhalZ3VGtGUmFVOXVkeTg0UTJsTVYz
      Y3hObTR2V1N0b2NGcFRTek5PV25vMmMwWmhhMFJsTlc5U04yTUtXWEpoVG1OV1FWQnphR1ZpY0V3
      d1JUTmllWHB1VjIwNFNYb3dWRGxUTWtKNlVFbE1TMFJLWkhaQ1JVNW1Va0k0VHpZMlV6QTVabUo2
      V1VzeVNFeFlPUXBDUkhKd09FeHlVV1V6V1RRell6aFpXbWRzVmxSdWNYVjNkbko0U0hCSmRWSkRh
      bVpDUjBSNmRsTnZaVU5CTnpCTU1qbFhNSGhuZG1SV01XbzRibkZWQ2paYWIweFdUaTlRYm0xR1ZV
      VkRPVWhyV1d3NVRYWnhOemxLVDBZeloydE1kMGxGWlV4RFJIa3hUM04wTm1kbU0xbERTakJpZEha
      cGFHZzNaSGcxY0ZvS2JrbFlNa3RPWm1weVdFbEZTM1pIT1hsMmJtdE9ieko0ZW1aQmIzTk9aM3Az
      WnpSMk5HSTRRVnBNYUhaMFpUa3ljSEZyZG1kRVJYbFVUVmxzZERNdlpBb3phREl4VVVwdlNXRnBV
      V3M0YlhwclRGaEtaM2xXYWpaeVUyeFNOWE5LYUhrd1ZXVlliRzlCT0hONmVIb3hkVWhqZG0xRU1G
      WkRZWEZLUTJVMk1rWXZDazlOVm10RlZHOUZkamhJY2xCeFRVcGxlR1YzUjFkbVQwWjViM2xoUldJ
      Mk1saHlSWE1yYnpsMFQzSlBORGd3TVVwaFZIazRVM1pHVnpSR1VqVTBhWE1LTlVRMk1XTnBXa0pU
      TDFwcFEyZHZOMlJ0V2sxMGNYZHRjazkxVm01dEwzRm9VVUZxTkhKNFRrcGhiRnBYWlVsUVZuY3JV
      MlIzVEdsU0x5ODRSbnB6WmdvM09XRmtTbUV4Y3pKcVVUWnRRbWRRUkZsV09TdHdjMnhSWVRFNVRE
      UklWVVkxWkdkbVFrbGhTVFZYVGpKTFdUUjNSelJzVlU5SFVETXhRelZUT1hWdkNsVm9MMWwxVkd4
      MlFXSkJZakJTVG1aWk5HZDBVa2N3U0hGWWMzQlhOVmR0U21aVmIwZGlaMEZuVm1wdmMzRTFZVmRH
      WW5CWFRWcG9VR2c1UmtKNU5XWUtXakptU0dwV2IxQnZVVGxYTUVkMmEwbE9kaXR1Y0hNMVpGWmxO
      V04zTVdaSWRraGpaMko1VTJWWGFsZzFhRTFVVkRoMFQycEZRazU2TnpscVUxaEpUZ3A0ZFRNMFVF
      NHJlbkZ4WXowS1BXeEJaM0lLTFMwdExTMUZUa1FnVUVkUUlGTkpSMDVCVkZWU1JTMHRMUzB0Q2c9
      PQ==
  tasks:
    - name: apply templated ostree remote config
      ansible.builtin.copy:
        content: "{{ ostree_remote_template }}"
        dest: /etc/ostree/remotes.d/rhel-edge.conf
    - name: run rpmostree update
      ansible.builtin.shell: rpm-ostree upgrade --allow-downgrade
      register: rpmostree_upgrade_out
      changed_when: '"No upgrade available" not in rpmostree_upgrade_out.stdout'
      failed_when: 'rpmostree_upgrade_out.rc != 0'
    - name: schedule reboot when rpmostree upgraded
      ansible.builtin.shell: systemd-run --on-active=5 /usr/bin/systemctl reboot
      when: '"Staging deployment...done" in rpmostree_upgrade_out.stdout'
