name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Display build environment
        run: printenv

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: install modules
        run: |
          [ $(go get -a | wc -l) -eq 0 ]

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --max-same-issues 20 --timeout 5m0s

      - name: Set up python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install openapi-spec-validator
        run: pip install openapi-spec-validator

      - name: Generate API docs spec file
        run: go run cmd/spec/main.go

      - name: Validate spec-file
        run: python3 -m openapi_spec_validator ${{ github.workspace }}/cmd/spec/openapi.json

      - name: Run coverage without fdo
        run: make coverage-no-fdo
